### ISSUE TITLE
Misleading log message

### ISSUE THREAD

**Issue by yorkish** [vpro/jcr-criteria#4]
This log seems misleading as the queryCount is always executed.

ro.jcr.criteria.advanced.impl.AdvancedCriteriaImpl: Total size was not available, determining it took 1341 ms

There isn't an alternative path that doesn't execute the queryCount.

**Comment by ricojansen** [comment]
I do think it is not always executed, as it is a lamba that will only be evaluated in the getTotalSize() method of nl.vpro.jcr.criteria.advanced.impl.AdvancedResultImpl in some cases
